client_config_backend: settings
client_config:
  client_id: your-client-id
  client_secret: your-client-secret

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json


oauth_scope:
  - https://www.googleapis.com/auth/drive.file
